---
title: "R Notebook"
output: html_notebook
---

### Task a)

We have S = suspectible for getting infected, I = infected, R = recovered/immune\
After studying the transition probability matrix we can conclude that the different parameters represents:\
$\beta$: The probability of getting infected $S \rightarrow$ I\$

$\gamma$: The probability of getting healty $I \rightarrow R$

$\alpha$: The probability of being not being immune anymore $R \rightarrow S$

### Task b)

With $\beta = 0.01$, $\gamma = 0.10$, $\alpha = 0.005$ we have the matrix:

We further have the possible states {S,I,R} as a result of $1 - \beta$, $1 - \gamma$, $1 - \alpha$ all being grater than $0$. Which means that the chain in aperiodic.

Further we have an finite, irreducible and aperiodic chain which means that we have a stationary distribution $\pi = (\pi_S,\pi_I,\pi_R)$.

If we further try to solve the equations $\pi = \pi P$ and $\sum \pi_i = 1$ which gives us the equations:

$\pi_S = \pi_S(1 -\beta) + \pi_R \alpha$ $\rightarrow$ $\pi_S = \pi_R \alpha$

$\pi_I = \pi_S \beta + \pi_I(1 - \gamma)$ $\rightarrow$ $\pi_I = \pi_S \beta$

Giving: $\pi_s = \frac{\beta}{\gamma} \pi_S$ and $\pi_R = \frac{\beta}{\alpha} \pi_S$

We also have: $ \pi_S + \pi_I + \pi_R = 1$ inserting the equations over we get:

$\pi_S(1 + \frac{\beta}{\gamma} + \frac{\beta}{\alpha}) = 1$

which means that: $\pi_S = \frac{1}{ 1 + \frac{\beta}{\gamma}+ \frac{\beta}{\alpha}}$

With $\frac{\beta}{\gamma} = 0.1$, $ \frac{\beta}{\alpha} = 2$ we get: $\pi_S = \frac{1}{3.1} = \frac{10}{31}$ , $\pi_I = \frac{1}{31}$ and $\pi_R = \frac{20}{31}$

If we assume a timestep is one day then the expected number of days in the different states are:

S: $365 \cot \frac{10}{31} = 117.7$ days

I: $365 \cdot \frac{1}{31} = 11.8$ days

R: $365 \cdot \frac{20}{31} = 235.5$ days
